### ISSUE TITLE
Serialized: Better support for read-and-write operations

### ISSUE THREAD

**Issue by mikolasstuchlik** [futuredapp/FTPropertyWrappers#39]
Lack of serialization of subsequent set and get operations (like subscript mutating access or mutating functions) may result in incorrect values. Further detail https://www.donnywals.com/why-your-atomic-property-wrapper-doesnt-work-for-collection-types/. 

- [ ] Expand currently supported mitigations methods by introducing `func asyncAccess(_ block: @escaping (inout Value)->Void )` and `func syncAccess<T>(_ block: @escaping (inout Value) -> T) -> T`
- [ ] Consider using throw/rethrow when implementing sync access.
- [ ] Expand existing documentation to further communicate the risks of read-and-write operations to the programmer via documentation and readme

**Comment by mkj-is** [comment]
This effort is not worth it anymore since this property wrapper is surpassed by introduction of actors in Swift 5.5.

https://github.com/apple/swift-evolution/blob/main/proposals/0306-actors.md
